# Linear Regression

## Mate data

In [3]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_features = boston.data 
boston_targets = boston.target

C:\Users\WenBi\anaconda3\envs\24723_Pytorch\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California

In [4]:
boston_features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
boston_targets

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

## Process data

In [8]:
# standar dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
boston_features = scaler.fit_transform(boston_features)
boston_features

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [11]:
# split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(boston_features,boston_targets,test_size=0.25)

## Train

### Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression

linear = LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [14]:
linear_predict = linear.predict(x_test)
linear_predict

array([27.42113556, 19.19358947, 31.78782075, 19.27376685, 22.38741206,
       24.63255585, 21.50459392, 16.49366565, 19.85029076, 30.73190958,
       34.77241609, 16.46339346, 26.96543222, 34.29806197, 23.1057942 ,
       26.57132431, 13.22678361, 23.53854259, 13.85377396, 24.75749478,
       12.55905428, 18.13146019, 31.83365307, 26.60012687, 21.35369968,
       13.30404226, 17.17160326, 22.25402431, 27.2193375 , 26.5483064 ,
       37.10474141, 36.52951644, 23.63031305, 42.11702116, 27.20902845,
        8.94622562, 10.15385305, 20.85798044, 32.52759268, 34.21965467,
       33.00755485, 21.84665953, 18.30381702, 24.73616089, 28.55958419,
       20.25623988, 32.36060962, 23.00336318, 22.32938349, 33.54754119,
       16.0653413 , 19.4869635 , 32.37606211, 22.47223052, 19.83890122,
       24.72744551, 26.94960343, 25.32012588, 16.34187038, 36.71435804,
       24.80239351, 18.67941366, 35.270351  , 17.96404189, 25.00762115,
       19.39329025, 32.55827774, 21.07587177, 16.56336128, 28.61

In [32]:
# accuracy evaluation
from sklearn.metrics import mean_absolute_error

linear_mean_absolute = mean_absolute_error(y_test,linear_predict)

In [33]:
from sklearn.metrics import mean_squared_error

linear_mean_squared = mean_squared_error(y_test,linear_predict)

### SGD

In [34]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()
sgd.fit(x_train,y_train.astype('str'))

SGDClassifier()

In [35]:
sgd_predict = sgd.predict(x_test.astype('int'))

In [36]:
# accuracy evaluation

sgd_mean_absolute = mean_absolute_error(y_test,sgd_predict)
sgd_mean_squared = mean_squared_error(y_test,sgd_predict)

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.

### 

In [21]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=10)
ridge.fit(x_train,y_train)

ridge_predict = ridge.predict(x_test)
ridge_mean_absolute = mean_absolute_error(y_test, ridge_predict)
# 均方误差
ridge_mean_squared = mean_squared_error(y_test,ridge_predict)

In [22]:
ridge_coef = ridge.coef_
ridge_coef

array([-0.51183158,  0.96476638,  0.02921901,  0.82362082, -1.58855719,
        2.66408495, -0.1438877 , -2.81217696,  1.66773088, -1.47222463,
       -2.1028448 ,  0.8628035 , -3.46914084])

In [23]:
ridge_intercept = ridge.intercept_